### ISSUE TITLE
Manter atualizados os atributos dos campeões

### ISSUE THREAD

**Issue by tekpixo** [tekpixo/moba.aid#12]
Desenvolver um _crawler_ dinâmico que mantém atualizadas as informações presentes no dataset (json).

**Comment by tekpixo** [comment]
É possível obter as informações atualizadas neste link: `http://ddragon.leagueoflegends.com/cdn/PATCH/data/en_US/champion.json` onde **PATCH** deve ser alterado pela versão presente do _game_ e.g. 9.3.1.

**Comment by tekpixo** [comment]
O **PATCH** atual pode ser obtido através do primeiro valor desse link `https://ddragon.leagueoflegends.com/api/versions.json`.

**Comment by tekpixo** [comment]
Atentar-se ao fato de que o json obtido via patch não possui todos os parâmetros necessários para o funcionamento da aplicação.

**Comment by tekpixo** [comment]
Crawler em perfeito funcionamento, consumindo dados do site [champion.gg](https://champion.gg).

**Comment by lincolncosta** [comment]
Utilizar [esse endpoint](https://flash.blitz.gg/graphql?query=query%20(%24region%3A%20String%2C%20%24language%3A%20String%2C%20%24queue%3A%20Int%2C%20%24tier%3A%20String%2C%20%24role%3A%20String%2C%20%24patch%3A%20String)%20%7B%0A%20%20lolChampionsListOverview(region%3A%20%24region%2C%20language%3A%20%24language%2C%20queue%3A%20%24queue%2C%20tier%3A%20%24tier%2C%20role%3A%20%24role%2C%20patch%3A%20%24patch)%20%7B%0A%20%20%20%20champion_id%0A%20%20%20%20champion%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20avatar%0A%20%20%20%20%20%20title%0A%20%20%20%20%20%20key%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20role%0A%20%20%20%20tier%0A%20%20%20%20total_game_count%0A%20%20%20%20stats%20%7B%0A%20%20%20%20%20%20winRate%0A%20%20%20%20%20%20pickRate%0A%20%20%20%20%20%20banRate%0A%20%20%20%20%20%20games%0A%20%20%20%20%20%20kda%0A%20%20%20%20%20%20totalDamageDealtToChampions%0A%20%20%20%20%20%20damageSelfMitigated%0A%20%20%20%20%20%20trueDamageDealtToChampions%0A%20%20%20%20%20%20heals%0A%20%20%20%20%20%20gold%0A%20%20%20%20%20%20creepScore%0A%20%20%20%20%20%20avgDamageToTurrets%0A%20%20%20%20%20%20averageGameTime%0A%20%20%20%20%20%20damage%0A%20%20%20%20%20%20damageTaken%0A%20%20%20%20%20%20averageGameSeconds%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20matchups%20%7B%0A%20%20%20%20%20%20champion%20%7B%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20avatar%0A%20%20%20%20%20%20%20%20key%0A%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20winRate%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20tier_ranks%20%7B%0A%20%20%20%20%20%20previous_tier_rank%0A%20%20%20%20%20%20tier_rank%0A%20%20%20%20%20%20status%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20__typename%0A%20%20%7D%0A%7D%0A&variables=%7B"language"%3A"en"%2C"role"%3A"ALL"%2C"region"%3A"world"%2C"queue"%3A420%2C"tier"%3A"PLATINUM_PLUS"%2C"patch"%3A"11.10"%7D) do Blitz.gg, alterando o parâmetro de PATCH conforme necessário. Para análise de sinergia entre campeões, utilizar [este endpoint](https://beta.iesdev.com/api/lolstats/duo/roles/TOP/SUPPORT?language=pt&region=world&patch=11.10&tier=PLATINUM_PLUS) alterando as rotas conforme necessário.
