### ISSUE TITLE
Reescrever documentação

### ISSUE THREAD

**Issue by tekpixo** [tekpixo/moba.aid#8]
Reescrever documentação explicando melhor os fluxos e os parâmetros necessários para execução. Também evidenciar quais são as saídas (arquivos com resultados) obtidas.

**Comment by santospatrick** [comment]
Tenho interesse em melhorar a documentação. Acredito que seria legal também criar uma versão CLI desse projeto e publicar em alguma store, para que usuários possam rodar os comandos sem nem precisar rodar um `npm install`. Já existem ferramentes no mercado que geram documentação e a flag `--help` com instruções automaticamente como [Inquirer](https://www.npmjs.com/package/inquirer) e [Yargs](http://yargs.js.org/)

**Comment by tekpixo** [comment]
@santospatrick, ótimas sugestões. Colaborações são sempre bem-vindas, fique à vontade caso queira aplicar as ferramentas que sugeriu.

Após melhorias no sentido de execução, também preciso melhorar a documentação do funcionamento do projeto.

**Comment by tekpixo** [comment]
Documentação atualizada à partir do commit https://github.com/tekpixo/moba.aid/commit/038eab80e220f440fc7d80f80019d3f551d4efb2.
